# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='hosted_by',
            new_name='host',
        ),
    ]
