# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_event_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.AddField(
            model_name='event',
            name='people_going',
            field=models.ManyToManyField(related_name='going', to=settings.AUTH_USER_MODEL),
        ),
    ]
