# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170618_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='event_photos/'),
        ),
    ]
